- app/src/main/java/ctrlcctrlv/happytraveller/activities/LogInActivity.java
- app/src/main/java/ctrlcctrlv/happytraveller/activities/WeatherActivity.java
- app/src/main/java/ctrlcctrlv/happytraveller/fragments/TabMapFragment.java
shows in map the user`s location and asks for gps permission
> current location

- app/src/main/java/ctrlcctrlv/happytraveller/animations/AnimatedButton.java
- app/src/main/java/ctrlcctrlv/happytraveller/fragments/TabMapFragment.java
- app/src/main/java/ctrlcctrlv/happytraveller/jsonParser/DirectionsParser.java
- app/src/main/java/ctrlcctrlv/happytraveller/url/CreateUrl.java
- app/src/main/res/layout/activity_maps.xml
- app/src/main/res/layout/fragment_tab_map.xml
+ A way to create route from users location to specific pin
+ Location listener that changes when users location is changing
+ New button on map with 2 options:
a) Just click that refreshes the route between user and pin
b) Long click to clear the map from pins and routes with a cool
animation on button
> New button on map , get route from users spot till a specific pin

- app/src/main/java/ctrlcctrlv/happytraveller/activities/HomeActivity.java
- app/src/main/java/ctrlcctrlv/happytraveller/fragments/TabMapFragment.java
- app/src/main/java/ctrlcctrlv/happytraveller/jsonParser/PlaceParser.java
- app/src/main/java/ctrlcctrlv/happytraveller/model/PlaceData.java
+Permission request from the beginning. (!!! Still bug that you need to restart the app exist !!! )
+Now user knows when he must press the sights button with a friendly message
> User now knows when to press the sights button

- app/src/main/AndroidManifest.xml
- app/src/main/java/ctrlcctrlv/happytraveller/activities/HomeActivity.java
- app/src/main/java/ctrlcctrlv/happytraveller/alterDialogs/HomeActivityAlterDialog.java
- app/src/main/java/ctrlcctrlv/happytraveller/connectivity/CheckConnection.java
+If users has not one of the two options to connect into the internet
applications pass him the question which one prefers to enable (Wifi or
data)
+For that purpose has been added one new class CheckConnection.java
> Check Users Connectivity to wifi ro data

- app/src/main/java/ctrlcctrlv/happytraveller/activities/MainActivity.java
- app/src/main/java/ctrlcctrlv/happytraveller/fragments/TabMapFragment.java
- app/src/main/java/ctrlcctrlv/happytraveller/url/RoutesUrl.java
If user checks on foot transport in side menu changes the route . Same if he checks car as transport
> change the route based on user`s transport

- .idea/misc.xml
- app/src/main/java/ctrlcctrlv/happytraveller/activities/MainActivity.java
- app/src/main/java/ctrlcctrlv/happytraveller/fragments/TabListViewFragment.java
- app/src/main/java/ctrlcctrlv/happytraveller/fragments/TabMapFragment.java
- app/src/main/java/ctrlcctrlv/happytraveller/jsonParser/PlaceParser.java
- app/src/main/java/ctrlcctrlv/happytraveller/model/PlaceData.java
- app/src/main/res/menu/menu_drawer.xml
> tabMapFragmentFor pins

- app/src/main/java/ctrlcctrlv/happytraveller/activities/HomeActivity.java
- app/src/main/java/ctrlcctrlv/happytraveller/activities/MainActivity.java
- app/src/main/java/ctrlcctrlv/happytraveller/adapters/ListItemAdapter.java
- app/src/main/java/ctrlcctrlv/happytraveller/fragments/TabMapFragment.java
- app/src/main/java/ctrlcctrlv/happytraveller/jsonParser/DirectionsParser.java
Fixed buggy sights(item) in navbar after clear button is long pressed
> Issue #31 Closed

- app/src/main/AndroidManifest.xml
- app/src/main/java/ctrlcctrlv/happytraveller/activities/HomeActivity.java
- app/src/main/java/ctrlcctrlv/happytraveller/activities/InfoActivity.java
- app/src/main/java/ctrlcctrlv/happytraveller/adapters/ListItemAdapter.java
- app/src/main/java/ctrlcctrlv/happytraveller/fragments/TabListViewFragment.java
- app/src/main/java/ctrlcctrlv/happytraveller/fragments/TabMapFragment.java
- app/src/main/res/layout/activity_info.xml
- app/src/main/res/layout/list_view.xml
- app/src/test/java/ctrlcctrlv/happytraveller/activities/LogInActivityTest.java
> Show routes(new)

- app/src/main/java/ctrlcctrlv/happytraveller/adapters/ListItemAdapter.java
- app/src/main/java/ctrlcctrlv/happytraveller/fragments/TabListViewFragment.java
- app/src/main/res/layout/list_view.xml
> Revert changes(themis)

- app/src/main/java/ctrlcctrlv/happytraveller/adapters/ListItemAdapter.java
- app/src/main/res/layout/list_view.xml
> changes for routes(reformed)

- .gitignore
- app/src/main/java/ctrlcctrlv/happytraveller/activities/DetailsActivity.java
> Details for placedata

- app/build.gradle
- app/google-services.json
- app/src/main/AndroidManifest.xml
- app/src/main/java/ctrlcctrlv/happytraveller/activities/LogInActivity.java
- app/src/main/java/ctrlcctrlv/happytraveller/activities/MainActivity.java
- app/src/main/java/ctrlcctrlv/happytraveller/activities/ResetPasswordActivity.java
- app/src/main/java/ctrlcctrlv/happytraveller/activities/SignUpActivity.java
- app/src/main/res/layout-v26/activity_log_in.xml
- app/src/main/res/layout/activity_log_in.xml
- app/src/main/res/layout/activity_sign_up.xml
- app/src/main/res/layout/nav_header.xml
- build.gradle
Create Database , connection Database, login and sign up done
> DB-LogIn/SignUp

- app/build.gradle
- app/src/main/java/ctrlcctrlv/happytraveller/activities/MainActivity.java
- app/src/main/java/ctrlcctrlv/happytraveller/adapters/ListItemAdapter.java
- app/src/main/java/ctrlcctrlv/happytraveller/connectivity/CheckConnection.java
- app/src/main/java/ctrlcctrlv/happytraveller/fragments/TabListViewFragment.java
- app/src/test/java/ctrlcctrlv/happytraveller/activities/MainActivityTest.java
- app/src/test/java/ctrlcctrlv/happytraveller/adapters/ListItemAdapterTest.java
- app/src/test/java/ctrlcctrlv/happytraveller/fragments/TabListViewFragmentTest.java
- app/src/test/java/ctrlcctrlv/happytraveller/url/PlaceUrlTest.java
Added test on mainActivity,TabListViewFragment,ListItemAdapter
> Added more testing

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/test/java/ctrlcctrlv/happytraveller/activities/HomeActivityTest.java
- app/src/test/java/ctrlcctrlv/happytraveller/activities/MainActivityTest.java
- app/src/test/java/ctrlcctrlv/happytraveller/fragments/TabMapFragmentTest.java
- app/src/test/java/ctrlcctrlv/happytraveller/jsonParser/PlaceParserTest.java
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
> Some testing and adding into build gradle

- app/src/androidTest/java/ctrlcctrlv/happytraveller/connectivity/CheckDataEnableBtn.java
- app/src/androidTest/java/ctrlcctrlv/happytraveller/connectivity/CheckGpsEnableBtn.java
- app/src/main/java/ctrlcctrlv/happytraveller/fragments/TabMapFragment.java
- app/src/test/java/ctrlcctrlv/happytraveller/google/RequestDirectionsTest.java
+Made some notes in order to run my esspreso test properly.
+Reforme some unit test  in order to run
> Esspresso and Unit testing fixes

- app/src/androidTest/java/ctrlcctrlv/happytraveller/activities/OverallTestingUI.java
- app/src/androidTest/java/ctrlcctrlv/happytraveller/activities/SightsButtonTest.java
overall ui testing and sight button test.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
> Espresso Testing(Themis)

- app/src/androidTest/java/ctrlcctrlv/happytraveller/activities/InfoButtonTestAndSights.java
- app/src/androidTest/java/ctrlcctrlv/happytraveller/activities/TestingCreateAccount.java
Added info button and create account test with espresso.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
> Espresso tests xaroula

- .idea/misc.xml
- app/src/main/java/ctrlcctrlv/happytraveller/activities/HomeActivity.java
- app/src/main/java/ctrlcctrlv/happytraveller/activities/MainActivity.java
- app/src/main/java/ctrlcctrlv/happytraveller/adapters/ListItemAdapter.java
- app/src/main/java/ctrlcctrlv/happytraveller/adapters/PageFragAdapter.java
- app/src/main/java/ctrlcctrlv/happytraveller/connectivity/CheckConnection.java
- app/src/main/java/ctrlcctrlv/happytraveller/fragments/TabListViewFragment.java
- app/src/main/java/ctrlcctrlv/happytraveller/jsonParser/PlaceParser.java
- app/src/main/java/ctrlcctrlv/happytraveller/model/PlaceData.java
- app/src/main/java/ctrlcctrlv/happytraveller/model/PlacePhoto.java
- app/src/main/java/ctrlcctrlv/happytraveller/url/PlaceUrl.java
Added JavaDoc comments my work especialy on:
+HomeActivity
+MainActivity
+ListItemAdapter
+PageFragAdapter
+CheckConnection
+TabListViewFragment
+PlaceParser
+PlaceData
+PlacePhoto
+PlaceUrl .
*Only my methods & variables  i did comments.
-Deleted some unused methods.
-Deleted and blank lines.
*My javadoc isnt on everything correct.Sorry
QLAMA TEAM.
> JavaDoc Comments

- app/src/main/java/ctrlcctrlv/happytraveller/activities/DetailsActivity.java
- app/src/main/java/ctrlcctrlv/happytraveller/activities/MainActivity.java
- app/src/main/java/ctrlcctrlv/happytraveller/activities/ShareActivity.java
last
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
> JAvadoc Xatzakos

- app/src/main/java/ctrlcctrlv/happytraveller/fragments/TabListViewFragment.java
- app/src/main/java/ctrlcctrlv/happytraveller/fragments/TabMapFragment.java
> javadoc-themis
